In [5]:
import pandas as pd
import numpy as np

import re
import nltk
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
#from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression

[nltk_data] Downloading package stopwords to C:\Users\Kumar
[nltk_data]     Shivam\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [60]:
df = pd.read_csv('Roman Urdu DataSet.csv',names=['state','rev','nan'],header=None,encoding='utf-8')
df.drop(columns='nan',inplace=True)
df.head()

state       rev
0  Sai kha ya her kisi kay bus ki bat nhi hai lak...  Positive
1                                          sahi bt h  Positive
2                                        Kya bt hai,  Positive
3                                         Wah je wah  Positive
4                               Are wha kaya bat hai  Positive

In [61]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Kumar
[nltk_data]     Shivam\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [62]:
# level 1 cleaning

lm = WordNetLemmatizer()
#ps = PorterStemmer()
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', str(df['state'][i]))
    review = review.lower()
    review = review.split()
    
    review = [lm.lemmatize(word) for word in review if not word in stopwords.words('english')]
    #review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [63]:
df.size

40458

In [64]:
len(corpus)

20229

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X = tf.fit_transform(corpus).toarray()

In [38]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
y=pd.get_dummies(df['rev'])
y=y.iloc[:,1].values

In [22]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=uint8)

In [23]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix

print("score",accuracy_score(y_pred,y_test)*100)

score 77.03905091448344


# Logistic Regression

In [46]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pre = model.predict(X_test)

In [48]:
print("score",accuracy_score(y_pre,y_test)*100)

score 78.6950074147306


In [51]:
model.predict_proba(X_test)

array([[0.82559704, 0.17440296],
       [0.89772833, 0.10227167],
       [0.75839789, 0.24160211],
       ...,
       [0.79743634, 0.20256366],
       [0.65297718, 0.34702282],
       [0.5587924 , 0.4412076 ]])

## Trying some thing

In [66]:
df1 = pd.DataFrame()
df1['st'] = corpus
df1['rev'] = df['rev']

df1.head()

st       rev
0  sai kha ya kisi kay bus ki bat nhi hai lakin m...  Positive
1                                          sahi bt h  Positive
2                                         kya bt hai  Positive
3                                         wah je wah  Positive
4                                   wha kaya bat hai  Positive

In [67]:
Independent_var = df1['st']
Dependent_var = df1['rev']

IV_train, IV_test, DV_train, DV_test = train_test_split(Independent_var, Dependent_var, test_size = 0.1, random_state = 225)

print('IV_train :', len(IV_train))
print('IV_test  :', len(IV_test))
print('DV_train :', len(DV_train))
print('DV_test  :', len(DV_test))

IV_train : 18206
IV_test  : 2023
DV_train : 18206
DV_test  : 2023


In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

tvec = TfidfVectorizer()
clf2 = LogisticRegression(solver = "lbfgs")




In [73]:
#model = Pipeline([('vectorizer',tvec),('classifier',clf2)])

model.fit(IV_train, DV_train)


from sklearn.metrics import confusion_matrix

predictions = model.predict(IV_test)

confusion_matrix(predictions, DV_test)

AttributeError: 'str' object has no attribute 'decode'

In [59]:
df1.isnull().sum()

st     0
rev    0
dtype: int64